- name: "Configure Minikube"
  hosts: all 
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  user: ubuntu 
  roles: 
    - configure-node