# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: mkhordoo/capstone
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout 
      - run:
          name: "Build Image" 
          command: |
            docker --version
            docker build -t $IMAGE_NAME:latest . 


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build