# Use the latest 2.1 version.. of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  lint:
    docker:
      - image: python:3.9-alpine
    steps:
      - checkout 
      - run:
          name: "Install dependencies" 
          command: |
            pip3 install -r requirements.txt
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - run:
          name: "lint"
          command: |  
            hadolint Dockerfile --ignore DL3013
            pylint --disable=R,C,W1203 app.py

  build-publish-docker-image:
    environment:
      IMAGE_NAME: mkhordoo/capstone
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout 
      - setup_remote_docker
      
      - run:
          name: "Build Image" 
          command: |
            docker --version
            docker build -t $IMAGE_NAME:latest . 
      
      - run:
          name: "Publish latest to docker hub" 
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker  push $IMAGE_NAME:latest
  
  create-master-node:
    environment:
      ANSIBLE_INVENTORY_PATH: /root/project/.circleci/ansible/inventory.txt
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout 
      - run:
          name: "Install dependencies" 
          command: |    
              yum install tar gzip -y 
      - run:
          name: "Deploy cloudformation stack" 
          command: |             
            aws cloudformation deploy --stack-name demo --template-file files/cluster.yaml 
      - run:
          name: "Add back-end ip to ansible inventory"
          command: |
            INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --output=text )   
            echo $INSTANCE_PUBLIC_IP
            echo "[all]" > .circleci/inventory.txt
            echo "${INSTANCE_PUBLIC_IP}" >> .circleci/inventory.txt
            cat .circleci/inventory.txt 
           
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/inventory.txt

  configure-master-node:
    docker:
      - image: lexauw/ansible-alpine
    steps:
      - checkout 
      - add_ssh_keys:
          fingerprints: ["a5:c1:42:5d:4b:2c:12:c8:75:66:63:b5:75:77:2b:20"]
      - attach_workspace:
          at: ~/
      - run:
          name: "Config by Ansible"
          command: |    
              ansible-playbook -i .circleci/inventory.txt .circleci/ansible/configure-kubernetes.yml


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      # - lint
      # - build-publish-docker-image:
      #     requires: [lint]
      - create-master-node
      #    requires: [build-publish-docker-image]
      # - create-master-node:
      #     requires: [create-master-node]
      - configure-master-node:
          requires: [create-master-node]
